/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextArea;

/**
 *
 * @author Charly Ponce
 */
public class FrmPrincipal extends javax.swing.JFrame {
    JFileChooser chooser;
    String rutaArchivoFuente;
    String rutaDirectorioDestino;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnalizar1 = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        BtnSelectDestino = new javax.swing.JButton();
        BtnSelectArchivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtCodigoFuente = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LbRutaArchivoFuente = new javax.swing.JLabel();
        LbRutaDirectorioDestino = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        btnAnalizar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnalizar1.setText("Archivo fuente");
        btnAnalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizar1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 560));
        setPreferredSize(new java.awt.Dimension(720, 560));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnalizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 158, -1));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 331, 310));

        BtnSelectDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnSelectDestino.setText("Ruta de destino");
        BtnSelectDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelectDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSelectDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 163, -1));

        BtnSelectArchivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnSelectArchivo.setText("Cargar archivo");
        BtnSelectArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelectArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSelectArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 163, -1));

        TxtCodigoFuente.setColumns(20);
        TxtCodigoFuente.setRows(5);
        jScrollPane2.setViewportView(TxtCodigoFuente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 310));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Codigo fuente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tokens");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        LbRutaArchivoFuente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LbRutaArchivoFuente.setText("Ruta...");
        getContentPane().add(LbRutaArchivoFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        LbRutaDirectorioDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LbRutaDirectorioDestino.setText("Ruta...");
        getContentPane().add(LbRutaDirectorioDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 105, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Analizador léxico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        try {
            if(rutaDirectorioDestino == null) {
                throw new FileNotFoundException();
            }
            // Variables para escribir los resultados del analisis lexico
            File archivo = new File(rutaDirectorioDestino + "/tokens.sim");                            
            PrintWriter escribir = new PrintWriter(archivo);            
            
            // Variables para hacer el analisis lexico
            Reader lector = new BufferedReader(new FileReader(rutaArchivoFuente));
            Lexer lexer = new Lexer(lector);
            String resultado = "";
            
            // Se hace el analisis lexico
            while (true) {
                Tokens tokens = lexer.yylex();
                if (tokens == null) {
                    txtResultado.setText(resultado);
                    escribir.print(resultado);
                    escribir.close();                    
                    return;
                }
                switch (tokens) {
                    case ERROR:
                        resultado += "Simbolo no definido\n";
                        break;
                    case Reservadas:
                        resultado += lexer.lexeme + "\n";
                        break;                        
                    case Suma: case Resta: case Multiplicacion: case Division:
                        resultado += "[op_ar]" + "\n";
                        break;                          
                    case Identificador:
                        resultado += "[id]\n";
                        break;
                    case Numero:
                        resultado += "[val]\n";
                        break;      
                     case MayorQue: case MenorQue:
                        resultado += "[op_rel]" + "\n";
                        break;       
                     case Asignacion:
                        resultado +=  "=\n";
                        break;     
                     case IgualA:
                        resultado +=  "==\n";
                        break;     
                     case LiteralDeTexto:
                        resultado +=  "[txt]\n";
                        break;                           
                     default:
                        resultado += "Simbolo desconocido\n";
                        break;                           
                }
            }
        }
        catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No haz escogido la ruta de destino", "Error", ERROR_MESSAGE);
        } 
        catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "No haz escogido un archivo para analizar", "ERROR", ERROR_MESSAGE);
        }        
        catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnAnalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizar1ActionPerformed

    private void BtnSelectDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelectDestinoActionPerformed
        rutaDirectorioDestino = seleccionarArchivo("Selecciona la ruta de destino", false);
        if(rutaDirectorioDestino != null) {
             getLbRutaDirectorioDestino().setText(rutaDirectorioDestino);           
        }
        else {
            getLbRutaDirectorioDestino().setText("Ruta...");            
        }        
    }//GEN-LAST:event_BtnSelectDestinoActionPerformed

    private void BtnSelectArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelectArchivoActionPerformed
        rutaArchivoFuente = seleccionarArchivo("Selecciona tu archivo", true);
        if(rutaArchivoFuente != null) {
             getLbRutaArchivoFuente().setText(rutaArchivoFuente); 
             getTxtCodigoFuente().setText("");
             cargarArchivo(rutaArchivoFuente, getTxtCodigoFuente());
             getTxtResultado().setText("");
        }
        else {
            getLbRutaArchivoFuente().setText("Ruta..."); 
            getTxtCodigoFuente().setText("");
            getTxtResultado().setText("");            
        }        
    }//GEN-LAST:event_BtnSelectArchivoActionPerformed
    
    public String seleccionarArchivo(String tituloVentana, boolean escogerArchivo) {
        String ruta = null;
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(tituloVentana);
        
        if(escogerArchivo) {
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);            
        }
        else {
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);            
        }
        // Desabilitar el "all files"
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta = chooser.getSelectedFile().getAbsolutePath();
        } 
        else {
            System.out.println("No se escogio un archivo ");
        }       
        
        return ruta;
    }
    
    public void cargarArchivo(String rutaArchivo, JTextArea TextArea) {
        BufferedReader reader;
        try {
            reader = new BufferedReader(new FileReader(rutaArchivo));
            String linea = reader.readLine();
            while (linea != null) {
                //System.out.println(linea);
                // Carga las lineas de texto del archivo al TextArea
                TextArea.setText(TextArea.getText() + linea + "\n");
                linea = reader.readLine();
            }
            reader.close();
        } 
        catch (IOException e) {
            e.printStackTrace();
        }    
    }

    public JTextArea getTxtResultado() {
        return txtResultado;
    }
    
    public JTextArea getTxtCodigoFuente() {
        return TxtCodigoFuente;
    }
    
    public JButton getBtnSelectArchivo() {
        return BtnSelectArchivo;
    }

    public JButton getBtnSelectDestino() {
        return BtnSelectDestino;
    }

    public JLabel getLbRutaArchivoFuente() {
        return LbRutaArchivoFuente;
    }

    public JLabel getLbRutaDirectorioDestino() {
        return LbRutaDirectorioDestino;
    }

    public JButton getBtnAnalizar() {
        return btnAnalizar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSelectArchivo;
    private javax.swing.JButton BtnSelectDestino;
    private javax.swing.JLabel LbRutaArchivoFuente;
    private javax.swing.JLabel LbRutaDirectorioDestino;
    private javax.swing.JTextArea TxtCodigoFuente;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnAnalizar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
