
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 05 17:21:29 CST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MayorQue = 10;
  public static final int PROGRAMA = 14;
  public static final int LEE = 25;
  public static final int FINPROG = 15;
  public static final int VECES = 21;
  public static final int Suma = 4;
  public static final int Numero = 9;
  public static final int LiteralDeTexto = 13;
  public static final int ENTONCES = 17;
  public static final int IMPRIME = 24;
  public static final int ERROR = 16;
  public static final int Identificador = 8;
  public static final int EOF = 0;
  public static final int SINO = 23;
  public static final int Division = 7;
  public static final int Resta = 5;
  public static final int SaltoDeLinea = 2;
  public static final int SI = 18;
  public static final int error = 1;
  public static final int FINREP = 22;
  public static final int IgualA = 12;
  public static final int Asignacion = 3;
  public static final int Multiplicacion = 6;
  public static final int MenorQue = 11;
  public static final int REPITE = 20;
  public static final int FINSI = 19;
}

