
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 09 19:46:56 CST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROGRAMA = 10;
  public static final int LEE = 21;
  public static final int FINPROG = 11;
  public static final int VECES = 17;
  public static final int Numero = 6;
  public static final int LiteralDeTexto = 9;
  public static final int ENTONCES = 13;
  public static final int IMPRIME = 20;
  public static final int ERROR = 12;
  public static final int Identificador = 5;
  public static final int OperadorAritmetico = 4;
  public static final int OperadorRelacional = 7;
  public static final int EOF = 0;
  public static final int SINO = 19;
  public static final int SaltoDeLinea = 2;
  public static final int SI = 14;
  public static final int error = 1;
  public static final int FINREP = 18;
  public static final int IgualA = 8;
  public static final int Asignacion = 3;
  public static final int REPITE = 16;
  public static final int FINSI = 15;
}

